NUMPY theory


In [1]:
import numpy as np

In [2]:
from time import process_time

time taken by list

In [3]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time -start_time)

0.0011845370000003186


numpy time taken

In [6]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array=np_array+1
end_time=process_time()
print(end_time-start_time)

0.0011753350000009988


numpy array

In [9]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

In [10]:
#creating a 1 dimensional
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)